services:
  db:
    container_name: db-odoo
    image: postgres:15-alpine
    restart: always
    command: -p 5441
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - odoo-net

  odoo:
    user: "101:101"
    container_name: saas-odoo
    image: odoo:17.0
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ./data/odoo:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    networks:
      - odoo-net

networks:
  odoo-net:
    driver: bridge
